export const users = [
  {
    id: 1,
    name: "Terrence",
    surname: "Manaka",
    age: 20,
    location: "Makgofe",
    gender: "Male",
  },
  {
    id: 2,
    name: "Ofentje",
    surname: "Phala",
    age: 15,
    location: "Tsate",
    gender: "Female",
  },
  {
    id: 3,
    name: "Uvehs",
    surname: "Patel",
    age: 17,
    location: "Giyane",
    gender: "Male",
  },
  {
    id: 4,
    name: "Johnny",
    surname: "Mahlakala",
    age: 17,
    location: "Makgofe",
    gender: "Male",
  },
  {
    id: 5,
    name: "Peter",
    surname: "Pan",
    age: 10,
    location: "Never Land",
    gender: "Male",
  },
  {
    id: 6,
    name: "Prudence",
    surname: "kgetsepe",
    age: 16,
    location: "Janefase",
    gender: "Female",
  },
  {
    id: 7,
    name: "Em",
    surname: "Stan",
    age: 16,
    location: "Janefase",
    gender: "Female",
  },
];
